import {
  AccessibilityHelp,
  Alignment,
  Autosave,
  Base64UploadAdapter,
  Bold,
  EditorConfig,
  Essentials,
  FontBackgroundColor,
  FontColor,
  FontColorConfig,
  FontFamily,
  FontSize,
  GeneralHtmlSupport,
  HorizontalLine,
  Image,
  ImageInsert,
  ImageInsertUI,
  ImageInsertViaUrl,
  ImageResize,
  ImageStyle,
  ImageToolbar,
  Indent,
  IndentBlock,
  Italic,
  LinkImage,
  List,
  ListProperties,
  PageBreak,
  Paragraph,
  SelectAll,
  ShowBlocks,
  SpecialCharacters,
  SpecialCharactersArrows,
  SpecialCharactersCurrency,
  SpecialCharactersEssentials,
  SpecialCharactersLatin,
  SpecialCharactersMathematical,
  SpecialCharactersText,
  Strikethrough,
  Style,
  Subscript,
  Superscript,
  Table,
  TableCaption,
  TableCellProperties,
  TableColumnResize,
  TableProperties,
  TableToolbar,
  TodoList,
  UiConfig,
  Underline,
  Undo,
} from 'ckeditor5';
import {Preview} from '../plugin/preview';
import {PageNumber} from '../plugin/page-number';
import {UserGuide} from '../plugin/user-guide';

const colorConfig: FontColorConfig = {
  colorPicker: {format: 'rgb'},
  colors: [
    {
      color: 'rgb(0, 0, 0)',
      label: 'Black',
    },
    {
      color: 'rgb(255, 255, 255)',
      label: 'White',
    },
    {
      color: 'rgb(230, 76, 76)',
      label: 'Red',
    },
    {
      color: 'rgb(230, 153, 76)',
      label: 'Orange',
    },
    {
      color: 'rgb(230, 230, 76)',
      label: 'Yellow',
    },
    {
      color: 'rgb(76, 230, 76)',
      label: 'Green',
    },
    {
      color: 'rgb(76, 76, 230)',
      label: 'Blue',
    },
    {
      color: 'rgb(153, 76, 230)',
      label: 'Purple',
    },
  ],
};

const uiConfig: UiConfig = {
  poweredBy: {
    forceVisible: false,
    position: 'inside',
    side: 'right',
    label: null,
    verticalOffset: 0,
    horizontalOffset: 0
  }
}

export const editorConfig: EditorConfig = {
  ui: uiConfig,
  toolbar: {
    items: [
      'fontSize',
      'fontFamily',
      'fontColor',
      'fontBackgroundColor',
      '|',
      'bold',
      'italic',
      'underline',
      'strikethrough',
      '|',
      'insertImage',
      'insertTable',
      'horizontalLine',
      '|',
      'alignment',
      '|',
      'bulletedList',
      'numberedList',
      'outdent',
      'indent',
      '|',
      'preview',
      'pageNumber',
      'userGuide'
    ],
    shouldNotGroupWhenFull: false,
  },
  plugins: [
    AccessibilityHelp,
    Alignment,
    Autosave,
    Base64UploadAdapter,
    Bold,
    Essentials,
    FontBackgroundColor,
    FontColor,
    FontFamily,
    FontSize,
    GeneralHtmlSupport,
    HorizontalLine,
    Image,
    ImageInsert,
    ImageInsertUI,
    ImageInsertViaUrl,
    ImageResize,
    ImageStyle,
    ImageToolbar,
    Indent,
    IndentBlock,
    Italic,
    LinkImage,
    List,
    ListProperties,
    PageBreak,
    Paragraph,
    SelectAll,
    ShowBlocks,
    SpecialCharacters,
    SpecialCharactersArrows,
    SpecialCharactersCurrency,
    SpecialCharactersEssentials,
    SpecialCharactersLatin,
    SpecialCharactersMathematical,
    SpecialCharactersText,
    Strikethrough,
    Style,
    Subscript,
    Superscript,
    Table,
    TableCaption,
    TableCellProperties,
    TableColumnResize,
    TableProperties,
    TableToolbar,
    TodoList,
    Underline,
    Undo,
  ],
  extraPlugins: [Preview, PageNumber, UserGuide],
  fontFamily: {
    options: [
      'Arial',
      'Helvetica',
      'Times New Roman',
      'Courier New',
    ]
  },
  fontSize: {
    options: [10, 12, 14, 'default', 18, 20, 22],
    supportAllValues: true,
  },
  fontColor: colorConfig,
  fontBackgroundColor: colorConfig,
  htmlSupport: {
    allow: [
      {
        name: /^.*$/,
        styles: true,
        attributes: true,
        classes: true,
      },
    ],
  },
  language: 'tr',
  list: {
    properties: {
      styles: true,
      startIndex: true,
      reversed: true,
    },
  },
  table: {
    contentToolbar: [
      'tableColumn',
      'tableRow',
      'mergeTableCells',
      'tableProperties',
      'tableCellProperties',
    ],
    tableCellProperties: {
      backgroundColors: colorConfig.colors,
      colorPicker: colorConfig.colorPicker,
      borderColors: colorConfig.colors,
    },
    tableProperties: {
      backgroundColors: colorConfig.colors,
      colorPicker: colorConfig.colorPicker,
      borderColors: colorConfig.colors,
    },
  },
  image: {
    resizeUnit: '%',
    toolbar: ['resizeImage:custom'],
    insert: {type: 'inline', integrations: ['upload', 'url']},
    upload: {types: ['jpeg', 'png', 'gif', 'tiff']},
  },
  translations: {
    "tr": {
      dictionary: {
        "Page Number": "Sayfa Numarası",
        "Preview": "Önizleme",
        "User Guide": "Kılavuz",
        "Words: %0": "Kelimeler: %0",
        "Characters: %0": "Karakterler: %0",
        "Widget toolbar": "Bileşen araç çubuğu",
        "Insert paragraph before block": "Bloktan önce paragraf ekle",
        "Insert paragraph after block": "Bloktan sonra paragraf ekle",
        "Press Enter to type after or press Shift + Enter to type before the widget": "Görsel bileşenden sonra yazmak için Enter'a basın ya da görsel bileşenden önce yazmak için Shift + Enter'a basın",
        "Keystrokes that can be used when a widget is selected (for example: image, table, etc.)": "Bir araç takımı seçildiğinde kullanılabilecek tuş vuruşları (örnek: resim, tablo vb.)",
        "Insert a new paragraph directly after a widget": "Araç takımının hemen sonrasına yeni bir paragraf ekle",
        "Insert a new paragraph directly before a widget": "Araç takımının hemen öncesine yeni bir paragraf ekle",
        "Move the caret to allow typing directly before a widget": "Bir araç takımından hemen önce yazmaya izin vermek için ekleme noktasını taşı",
        "Move the caret to allow typing directly after a widget": "Bir araç takımından hemen sonra yazmaya izin vermek için ekleme noktasını taşı",
        "Move focus from an editable area back to the parent widget": "Odağı düzenlenebilir bir alandan üst pencere öğesine geri taşıyın",
        "Upload in progress": "Yükleme işlemi devam ediyor",
        "Undo": "Geri al",
        "Redo": "Tekrar yap",
        "Rich Text Editor": "Zengin İçerik Editörü",
        "Editor editing area: %0": "Editör düzenleme alanı: %0",
        "Edit block": "Bloğu Düzenle",
        "Click to edit block": "Bloğu düzenlemek için tıkla",
        "Drag to move": "Taşımak için sürükle",
        "Next": "Sonraki",
        "Previous": "Önceki",
        "Editor toolbar": "Düzenleme araç çubuğu",
        "Dropdown toolbar": "Açılır araç çubuğu",
        "Black": "Siyah",
        "Dim grey": "Koyu Gri",
        "Grey": "Gri",
        "Light grey": "Açık Gri",
        "White": "Beyaz",
        "Red": "Kırmızı",
        "Orange": "Turuncu",
        "Yellow": "Sarı",
        "Light green": "Açık Yeşil",
        "Green": "Yeşil",
        "Aquamarine": "Su Yeşili",
        "Turquoise": "Turkuaz",
        "Light blue": "Açık Mavi",
        "Blue": "Mavi",
        "Purple": "Mor",
        "Editor block content toolbar": "Düzenleyici engelleme içerik araç çubuğu",
        "Editor contextual toolbar": "Düzenleyici içeriksel araç çubuğu",
        "HEX": "ONALTILIK",
        "No results found": "Sonuç bulunamadı",
        "No searchable items": "Aranabilir öge yok",
        "Editor dialog": "Düzenleyici iletişim kutusu",
        "Close": "Kapat",
        "Help Contents. To close this dialog press ESC.": "Yardım İçerikleri. Bu iletişim kutusunu kapatmak için ESC tuşuna basın.",
        "Below, you can find a list of keyboard shortcuts that can be used in the editor.": "Aşağıda editörde kullanılabilecek klavye kısayollarının bir listesini bulabilirsiniz.",
        "(may require <kbd>Fn</kbd>)": "(<kbd>Fn</kbd> gerekebilir)",
        "Accessibility": "Erişilebilirlik",
        "Accessibility help": "Erişilebilirlik yardımı",
        "Press %0 for help.": "Yardım için %0 tuşuna basın.",
        "Move focus in and out of an active dialog window": "Odağı etkin iletişim penceresinin içine ve dışına taşı",
        "MENU_BAR_MENU_FILE": "Dosya",
        "MENU_BAR_MENU_EDIT": "Düzenle",
        "MENU_BAR_MENU_VIEW": "Görüntüle",
        "MENU_BAR_MENU_INSERT": "Ekle",
        "MENU_BAR_MENU_FORMAT": "Biçim",
        "MENU_BAR_MENU_TOOLS": "Araçlar",
        "MENU_BAR_MENU_HELP": "Yardım",
        "MENU_BAR_MENU_TEXT": "Metin",
        "MENU_BAR_MENU_FONT": "Yazı Tipi",
        "Editor menu bar": "Düzenleyici menü çubuğu",
        "Please enter a valid color (e.g. \"ff0000\").": "Lütfen geçerli bir renk girin (ör. \"ff0000\").",
        "Insert table": "Tablo Ekle",
        "Header column": "Başlık kolonu",
        "Insert column left": "Sola kolon ekle",
        "Insert column right": "Sağa kolon ekle",
        "Delete column": "Kolonu sil",
        "Select column": "Kolon seç",
        "Column": "Kolon",
        "Header row": "Başlık satırı",
        "Insert row below": "Alta satır ekle",
        "Insert row above": "Üste satır ekle",
        "Delete row": "Satırı sil",
        "Select row": "Satır seç",
        "Row": "Satır",
        "Merge cell up": "Yukarı doğru birleştir",
        "Merge cell right": "Sağa doğru birleştir",
        "Merge cell down": "Aşağıya doğru birleştir",
        "Merge cell left": "Sola doğru birleştir",
        "Split cell vertically": "Hücreyi dikey böl",
        "Split cell horizontally": "Hücreyi yatay böl",
        "Merge cells": "Hücreleri birleştir",
        "Table toolbar": "Tablo araç çubuğu",
        "Table properties": "Tablo özellikleri",
        "Cell properties": "Hücre özellikleri",
        "Border": "Kenar",
        "Style": "Stil",
        "Width": "Genişlik",
        "Height": "Yükseklik",
        "Color": "Renk",
        "Background": "Arkaplan",
        "Padding": "İç boşluk",
        "Dimensions": "Ölçüler",
        "Table cell text alignment": "Tablo hücresi metin hizalaması",
        "Alignment": "Hizalama",
        "Horizontal text alignment toolbar": "Yatay metin hizalama araç çubuğu",
        "Vertical text alignment toolbar": "Dikey metin hizalama araç çubuğu",
        "Table alignment toolbar": "Tablo hizalama araç çubuğu",
        "None": "Yok",
        "Solid": "Dolu",
        "Dotted": "Noktalı",
        "Dashed": "Kesik çizgili",
        "Double": "Çift",
        "Groove": "Yiv",
        "Ridge": "Yükselti",
        "Inset": "İçe",
        "Outset": "Dışarıya",
        "Align cell text to the left": "Hücre içindeki metnini sola hizala",
        "Align cell text to the center": "Hücre içindeki metnini ortaya hizalama",
        "Align cell text to the right": "Hücre içindeki metnini sağa hizala",
        "Justify cell text": "Hücre içindeki metini iki yana yasla",
        "Align cell text to the top": "Hücre içindeki metni üste hizala",
        "Align cell text to the middle": "Hücre içindeki metni ortaya hizala",
        "Align cell text to the bottom": "Hücre içindeki metni alta hizala",
        "Align table to the left": "Tabloyu sola hizala",
        "Center table": "Tabloyu ortala",
        "Align table to the right": "Tabloyu sağa hizala",
        "The color is invalid. Try \"#FF0000\" or \"rgb(255,0,0)\" or \"red\".": "Geçersiz renk. \"#FF0000\" veya \"rgb(255,0,0)\" veya \"red\" deneyin.",
        "The value is invalid. Try \"10px\" or \"2em\" or simply \"2\".": "Geçersiz değer. \"10px\" veya \"2em\" veya sadece \"2\" deneyin.",
        "Color picker": "Renk seçici",
        "Enter table caption": "Tablo açıklaması gir",
        "Keystrokes that can be used in a table cell": "Tablo hücresinde kullanılabilecek tuş vuruşları",
        "Move the selection to the next cell": "Seçimi sonraki hücreye taşı",
        "Move the selection to the previous cell": "Seçimi önceki hücreye taşı",
        "Insert a new table row (when in the last cell of a table)": "Yeni bir tablo satırı ekle (tablonun son hücresindeyken)",
        "Navigate through the table": "Tabloda gezin",
        "Table": "Tablo",
        "Styles": "Stiller",
        "Multiple styles": "Birden fazla stil",
        "Block styles": "Blok stilleri",
        "Text styles": "Metin stilleri",
        "Special characters": "Özel karakterler",
        "All": "Tümü",
        "Arrows": "Oklar",
        "Currency": "Para Birimi",
        "Latin": "Latince",
        "Mathematical": "Matematiksel",
        "Text": "Metin",
        "leftwards simple arrow": "sola doğru basit ok",
        "rightwards simple arrow": "sağa doğru basit ok",
        "upwards simple arrow": "yukarı doğru basit ok",
        "downwards simple arrow": "aşağı doğru basit ok",
        "leftwards double arrow": "sola çift ok",
        "rightwards double arrow": "sağa çift ok",
        "upwards double arrow": "yukarı çift ok",
        "downwards double arrow": "aşağı çift ok",
        "leftwards dashed arrow": "sola kesik çizgili ok",
        "rightwards dashed arrow": "sağa kesik çizgili ok",
        "upwards dashed arrow": "yukarı doğru kesik ok",
        "downwards dashed arrow": "aşağı doğru kesik ok",
        "leftwards arrow to bar": "sola ok çubuğu",
        "rightwards arrow to bar": "sağa ok çubuğu",
        "upwards arrow to bar": "yukarı ok çubuğu",
        "downwards arrow to bar": "aşağı ok çubuğu",
        "up down arrow with base": "taban ile yukarı aşağı ok",
        "back with leftwards arrow above": "geri sol ok yukarıda",
        "end with leftwards arrow above": "sona sol ok yukarıda",
        "on with exclamation mark with left right arrow above": "üzerinde sol sağ ok bulunan ünlem işaretiyle",
        "soon with rightwards arrow above": "yakında sağ ok ile",
        "top with upwards arrow above": "en üst yukarı oku",
        "Dollar sign": "Dolar işareti",
        "Euro sign": "Avro işareti",
        "Yen sign": "Yen işareti",
        "Pound sign": "Sterlin işareti",
        "Cent sign": "Kuruş işareti",
        "Euro-currency sign": "Avro para birimi simgesi",
        "Colon sign": "İki nokta üst üste işareti",
        "Cruzeiro sign": "Cruzeiro işareti",
        "French franc sign": "Fransız Frangı işareti",
        "Lira sign": "Lira işareti",
        "Currency sign": "Para birimi işareti",
        "Bitcoin sign": "Bitcoin işareti",
        "Mill sign": "Mill işareti",
        "Naira sign": "Naira işareti",
        "Peseta sign": "Peseta işareti",
        "Rupee sign": "Rupi işareti",
        "Won sign": "Kazanılan işaret",
        "New sheqel sign": "Yeni şekel işareti",
        "Dong sign": "Dong işareti",
        "Kip sign": "Kip işareti",
        "Tugrik sign": "Tugrik işareti",
        "Drachma sign": "Drahmisi işareti",
        "German penny sign": "Alman kuruş işareti",
        "Peso sign": "Peso işareti",
        "Guarani sign": "Guarani işareti",
        "Austral sign": "Austral işareti",
        "Hryvnia sign": "Grivnası işareti",
        "Cedi sign": "Cedi işareti",
        "Livre tournois sign": "Livre tournois işareti",
        "Spesmilo sign": "Spesmilo işareti",
        "Tenge sign": "Tenge işareti",
        "Indian rupee sign": "Hint Rupisi işareti",
        "Turkish lira sign": "Türk Lirası işareti",
        "Nordic mark sign": "İskandinav işareti",
        "Manat sign": "Manat işareti",
        "Ruble sign": "Ruble işareti",
        "Latin capital letter a with macron": "Üstü çizili büyük a harfi",
        "Latin small letter a with macron": "Üstü çizili küçük a harfi",
        "Latin capital letter a with breve": "Üstü yuvarlak büyük a harfi",
        "Latin small letter a with breve": "Üstü yuvarlak küçük a harfi",
        "Latin capital letter a with ogonek": "Altı kuyruklu işaretli büyük a harfi",
        "Latin small letter a with ogonek": "Altı kuyruklu işaretli küçük a harfi",
        "Latin capital letter c with acute": "Üzeri tırnaklı büyük c harfi",
        "Latin small letter c with acute": "Üzeri tırnaklı küçük c harfi",
        "Latin capital letter c with circumflex": "Üzeri şapkalı büyük c harfi",
        "Latin small letter c with circumflex": "Üzeri şapkalı küçük c harfi",
        "Latin capital letter c with dot above": "Üstü noktalı büyük c harfi",
        "Latin small letter c with dot above": "Üstü noktalı küçük c harfi",
        "Latin capital letter c with caron": "Üstü ters şapkalı büyük c harfi",
        "Latin small letter c with caron": "Üstü ters şapkalı küçük c harfi",
        "Latin capital letter d with caron": "Üstü ters şapkalı büyük d harfi",
        "Latin small letter d with caron": "Üstü ters şapkalı küçük d harfi",
        "Latin capital letter d with stroke": "Ortası çizgili büyük d harfi",
        "Latin small letter d with stroke": "Ortası çizgili küçük d harfi",
        "Latin capital letter e with macron": "Üstü çizili büyük e harfi",
        "Latin small letter e with macron": "Üstü çizili küçük e harfi",
        "Latin capital letter e with breve": "Üstü ters şapkalı büyük e harfi",
        "Latin small letter e with breve": "Üstü ters şapkalı küçük e harfi",
        "Latin capital letter e with dot above": "Üstü noktalı büyük e harfi",
        "Latin small letter e with dot above": "Üstü noktalı küçük e harfi",
        "Latin capital letter e with ogonek": "Altı kuyruklu büyük e harfi",
        "Latin small letter e with ogonek": "Altı kuyruklu küçük e harfi",
        "Latin capital letter e with caron": "Üstü ters şapkalı büyük e harfi",
        "Latin small letter e with caron": "Üstü ters şapkalı küçük e harfi",
        "Latin capital letter g with circumflex": "Üzeri şapkalı büyük g harfi",
        "Latin small letter g with circumflex": "Üzeri şapkalı küçük g harfi",
        "Latin capital letter g with breve": "Üstü ters şapkalı büyük g harfi",
        "Latin small letter g with breve": "Üstü ters şapkalı küçük g harfi",
        "Latin capital letter g with dot above": "Üstü noktalı büyük g harfi",
        "Latin small letter g with dot above": "Üstü noktalı küçük g harfi",
        "Latin capital letter g with cedilla": "Altı kuyruklu büyük g harfi",
        "Latin small letter g with cedilla": "Altı kuyruklu küçük g harfi",
        "Latin capital letter h with circumflex": "Üzeri şapkalı büyük h harfi",
        "Latin small letter h with circumflex": "Üzeri şapkalı küçük g harfi",
        "Latin capital letter h with stroke": "Üst kısmı çizgili büyük h harfi",
        "Latin small letter h with stroke": "Üst kısmı çizgili küçük h harfi",
        "Latin capital letter i with tilde": "Üstü tilda işaretli büyük i harfi",
        "Latin small letter i with tilde": "Üstü tilda işaretli küçük i harfi",
        "Latin capital letter i with macron": "Üstü çizili büyük i harfi",
        "Latin small letter i with macron": "Üstü çizili küçük i harfi",
        "Latin capital letter i with breve": "Üstü ters şapkalı büyük i harfi",
        "Latin small letter i with breve": "Üstü ters şapkalı küçük i harfi",
        "Latin capital letter i with ogonek": "Altı kuyruklu büyük i harfi",
        "Latin small letter i with ogonek": "Altı kuyruklu küçük i harfi",
        "Latin capital letter i with dot above": "Üstü noktalı büyük i harfi",
        "Latin small letter dotless i": "Noktası küçük i harfi",
        "Latin capital ligature ij": "Büyük ij harfi",
        "Latin small ligature ij": "Küçük ij harfi",
        "Latin capital letter j with circumflex": "Üzeri şapkalı büyük j harfi",
        "Latin small letter j with circumflex": "Üzeri şapkalı küçük j harfi",
        "Latin capital letter k with cedilla": "Altı kuyruklu büyük k harfi",
        "Latin small letter k with cedilla": "Altı kuyruklu küçük k harfi",
        "Latin small letter kra": "Küçük küt k harfi",
        "Latin capital letter l with acute": "Üzeri tırnaklı büyük L harfi",
        "Latin small letter l with acute": "Üzeri tırnaklı küçük L harfi",
        "Latin capital letter l with cedilla": "Altı kuyruklu büyük L harfi",
        "Latin small letter l with cedilla": "Altı kuyruklu küçük L harfi",
        "Latin capital letter l with caron": "Üstü ters şapkalı büyük L harfi",
        "Latin small letter l with caron": "Üstü ters şapkalı küçük L harfi",
        "Latin capital letter l with middle dot": "Ortası noktalı büyük L harfi",
        "Latin small letter l with middle dot": "Ortası noktalı küçük L harfi",
        "Latin capital letter l with stroke": "Üst kısmı çizgili büyük L harfi",
        "Latin small letter l with stroke": "Üst kısmı çizgili küçük L harfi",
        "Latin capital letter n with acute": "Üzeri tırnaklı büyük n harfi",
        "Latin small letter n with acute": "Üzeri tırnaklı küçük n harfi",
        "Latin capital letter n with cedilla": "Altı kuyruklu büyük n harfi",
        "Latin small letter n with cedilla": "Altı kuyruklu küçük n harfi",
        "Latin capital letter n with caron": "Üstü ters şapkalı büyük n harfi",
        "Latin small letter n with caron": "Üstü ters şapkalı küçük n harfi",
        "Latin small letter n preceded by apostrophe": "Önden apostrof küçük n harfi",
        "Latin capital letter eng": "Alttan kuyruklu büyük n harfi",
        "Latin small letter eng": "Alttan kuyruklu küçük n harfi",
        "Latin capital letter o with macron": "Üstü çizili büyük o harfi",
        "Latin small letter o with macron": "Üstü çizili küçük o harfi",
        "Latin capital letter o with breve": "Üstü ters şapkalı büyük o harfi",
        "Latin small letter o with breve": "Üstü ters şapkalı küçük o harfi",
        "Latin capital letter o with double acute": "Üstü çift tırnaklı büyük o harfi",
        "Latin small letter o with double acute": "Üstü çift tırnaklı küçük o harfi",
        "Latin capital ligature oe": "Büyük yunan OE harfi",
        "Latin small ligature oe": "Küçük yunan OE harfi",
        "Latin capital letter r with acute": "Üzeri tırnaklı büyük r harfi",
        "Latin small letter r with acute": "Üzeri tırnaklı küçük r harfi",
        "Latin capital letter r with cedilla": "Altı kuyruklu büyük r harfi",
        "Latin small letter r with cedilla": "Altı kuyruklu küçük r harfi",
        "Latin capital letter r with caron": "Üstü ters şapkalı büyük r harfi",
        "Latin small letter r with caron": "Üstü ters şapkalı küçük r harfi",
        "Latin capital letter s with acute": "Üzeri tırnaklı büyük s harfi",
        "Latin small letter s with acute": "Üzeri tırnaklı küçük s harfi",
        "Latin capital letter s with circumflex": "Üzeri şapkalı büyük s harfi",
        "Latin small letter s with circumflex": "Üzeri şapkalı küçük s harfi",
        "Latin capital letter s with cedilla": "Altı kuyruklu büyük s harfi",
        "Latin small letter s with cedilla": "Altı kuyruklu küçük s harfi",
        "Latin capital letter s with caron": "Üstü ters şapkalı büyük s harfi",
        "Latin small letter s with caron": "Üstü ters şapkalı küçük s harfi",
        "Latin capital letter t with cedilla": "Altı kuyruklu büyük t harfi",
        "Latin small letter t with cedilla": "Altı kuyruklu küçük t harfi",
        "Latin capital letter t with caron": "Üstü ters şapkalı büyük t harfi",
        "Latin small letter t with caron": "Üstü ters şapkalı küçük t harfi",
        "Latin capital letter t with stroke": "Üst kısmı çizgili büyük t harfi",
        "Latin small letter t with stroke": "Üst kısmı çizgili küçük t harfi",
        "Latin capital letter u with tilde": "Üstü tildalı büyük u harfi",
        "Latin small letter u with tilde": "Üstü tildalı küçük u harfi",
        "Latin capital letter u with macron": "Üstü çizili büyük u harfi",
        "Latin small letter u with macron": "Üstü çizili küçük u harfi",
        "Latin capital letter u with breve": "Üstü ters şapkalı büyük u harfi",
        "Latin small letter u with breve": "Üstü ters şapkalı küçük u harfi",
        "Latin capital letter u with ring above": "Üstü derece işaretli büyük u harfi",
        "Latin small letter u with ring above": "Üstü derece işaretli küçük u harfi",
        "Latin capital letter u with double acute": "Üstü çift tırnaklı büyük u harfi",
        "Latin small letter u with double acute": "Üstü çift tırnaklı küçük u harfi",
        "Latin capital letter u with ogonek": "Altı kuyruklu büyük u harfi",
        "Latin small letter u with ogonek": "Altı kuyruklu küçük u harfi",
        "Latin capital letter w with circumflex": "Üzeri şapkalı büyük w harfi",
        "Latin small letter w with circumflex": "Üzeri şapkalı küçük w harfi",
        "Latin capital letter y with circumflex": "Üzeri şapkalı büyük y harfi",
        "Latin small letter y with circumflex": "Üzeri şapkalı küçük y harfi",
        "Latin capital letter y with diaeresis": "Üstü çift noktalı büyük y harfi",
        "Latin capital letter z with acute": "Üzeri tırnaklı büyük z harfi",
        "Latin small letter z with acute": "Üzeri tırnaklı küçük z harfi",
        "Latin capital letter z with dot above": "Üstü noktalı büyük z harfi",
        "Latin small letter z with dot above": "Üstü noktalı küçük z harfi",
        "Latin capital letter z with caron": "Üstü ters şapkalı büyük z harfi",
        "Latin small letter z with caron": "Üstü ters şapkalı küçük z harfi",
        "Latin small letter long s": "Uzun küçük s harfi",
        "Less-than sign": "Küçüktür işareti",
        "Greater-than sign": "Büyüktür işareti",
        "Less-than or equal to": "Küçük veya eşit",
        "Greater-than or equal to": "Büyük veya eşit",
        "En dash": "Çizgi",
        "Em dash": "Uzun çizgi",
        "Macron": "Uzatma işareti",
        "Overline": "Üstü çizili",
        "Degree sign": "Derece işareti",
        "Minus sign": "Eksi işareti",
        "Plus-minus sign": "Artı eksi işareti",
        "Division sign": "Bölme işareti",
        "Fraction slash": "Kesir eğik çizgi",
        "Multiplication sign": "Çarpma işareti",
        "Latin small letter f with hook": "Latince küçük f harfi",
        "Integral": "İntegral",
        "N-ary summation": "N-ary toplamı",
        "Infinity": "Sonsuzluk",
        "Square root": "Kare kök",
        "Tilde operator": "Tilde operatörü",
        "Approximately equal to": "Yaklaşık olarak eşit",
        "Almost equal to": "Neredeyse eşit",
        "Not equal to": "Eşit değil",
        "Identical to": "Benzeri",
        "Element of": "Öğesi",
        "Not an element of": "Onun öğesi değil",
        "Contains as member": "Üye olarak içerir",
        "N-ary product": "N-ary ürünü",
        "Logical and": "Mantıksal VE",
        "Logical or": "Mantıksal VEYA",
        "Not sign": "İmzalanmamış",
        "Intersection": "Kesişim",
        "Union": "Birleşik",
        "Partial differential": "Kısmi diferansiyel",
        "For all": "Hepsi için",
        "There exists": "Var",
        "Empty set": "Boş küme",
        "Nabla": "Nabla",
        "Asterisk operator": "Yıldız operatörü",
        "Proportional to": "Orantılı",
        "Angle": "Açı",
        "Vulgar fraction one quarter": "Kaba kesir bir çeyrek",
        "Vulgar fraction one half": "Kaba kesir bir buçuk",
        "Vulgar fraction three quarters": "Kaba bölüm dörtte üç",
        "Single left-pointing angle quotation mark": "Tek sola dönük açı tırnak işareti",
        "Single right-pointing angle quotation mark": "Sağa bakan tek açılı tırnak işareti",
        "Left-pointing double angle quotation mark": "Sola dönük çift açılı tırnak işareti",
        "Right-pointing double angle quotation mark": "Sağa bakan çift açılı tırnak işareti",
        "Left single quotation mark": "Sol tek tırnak işareti",
        "Right single quotation mark": "Sağ tek tırnak işareti",
        "Left double quotation mark": "Sol çift tırnak işareti",
        "Right double quotation mark": "Sağ çift tırnak işareti",
        "Single low-9 quotation mark": "Tek düşük 9 tırnak işareti",
        "Double low-9 quotation mark": "Çift düşük 9 tırnak işareti",
        "Inverted exclamation mark": "Ters ünlem işareti",
        "Inverted question mark": "Ters soru işareti",
        "Two dot leader": "Öncelikli iki nokta",
        "Horizontal ellipsis": "Yatay elips",
        "Double dagger": "Çift hançer",
        "Per mille sign": "Bin işareti için",
        "Per ten thousand sign": "Her on bine göre işareti",
        "Double exclamation mark": "Çift ünlem işareti",
        "Question exclamation mark": "Soru ünlem işareti",
        "Exclamation question mark": "Ünlem soru işareti",
        "Double question mark": "Çift soru işareti",
        "Copyright sign": "Telif hakkı işareti",
        "Registered sign": "Kayıtlı işareti",
        "Trade mark sign": "Ticari marka işareti",
        "Section sign": "Bölüm işareti",
        "Paragraph sign": "Paragraf işareti",
        "Reversed paragraph sign": "Ters paragraf işareti",
        "Character categories": "Karakter kategorileri",
        "Source": "Kaynak",
        "Show source": "Kaynağı göster",
        "Show blocks": "Blokları göster",
        "Select all": "Hepsini seç",
        "Disable editing": "Düzenlemeyi devre dışı bırak",
        "Enable editing": "Düzenlemeyi etkinleştir",
        "Previous editable region": "Önceki düzenlenebilir alan",
        "Next editable region": "Sonraki düzenlenebilir alan",
        "Navigate editable regions": "Düzenlenebilir alanlara git",
        "Remove Format": "Biçimlendirmeyi Kaldır",
        "Page break": "Sayfa sonu",
        "media widget": "medya aracı",
        "Media URL": "Medya URL'si",
        "Paste the media URL in the input.": "Medya URL'siini metin kutusuna yapıştırınız.",
        "Tip: Paste the URL into the content to embed faster.": "İpucu: İçeriği daha hızlı yerleştirmek için URL'yi yapıştırın.",
        "The URL must not be empty.": "URL boş olamaz.",
        "This media URL is not supported.": "Desteklenmeyen Medya URL'si.",
        "Insert media": "Medya Ekle",
        "Media": "Medya",
        "Media toolbar": "Medya araç çubuğu",
        "Open media in new tab": "Medyayı yeni sekmede aç",
        "Numbered List": "Numaralı Liste",
        "Bulleted List": "Simgeli Liste",
        "To-do List": "Yapılacaklar Listesi",
        "Bulleted list styles toolbar": "Madde işaretli liste stilleri araç çubuğu",
        "Numbered list styles toolbar": "Numaralandırılmış liste stilleri araç çubuğu",
        "Toggle the disc list style": "Disk liste stilini değiştir",
        "Toggle the circle list style": "Çember liste stilini değiştir",
        "Toggle the square list style": "Kare liste stilini değiştir",
        "Toggle the decimal list style": "Ondalık liste stilini değiştir",
        "Toggle the decimal with leading zero list style": "0'la başlayan ondalık liste stilini değiştir",
        "Toggle the lower–roman list style": "Küçük Roma rakamları liste stilini değiştir",
        "Toggle the upper–roman list style": "Büyük Roma rakamları liste stilini değiştir",
        "Toggle the lower–latin list style": "Küçük Latin harfleri liste stilini değiştir",
        "Toggle the upper–latin list style": "Büyük Latin harfleri liste stilini değiştir",
        "Disc": "Disk",
        "Circle": "Çember",
        "Square": "Kare",
        "Decimal": "Ondalık",
        "Decimal with leading zero": "0'la başlayan ondalık",
        "Lower–roman": "Küçük Roma rakamları",
        "Upper-roman": "Büyük Roma rakamları",
        "Lower-latin": "Küçük Latin harfleri",
        "Upper-latin": "Büyük Latin harfleri",
        "List properties": "Liste özellikleri",
        "Start at": "Şununla başla",
        "Invalid start index value.": "Geçersiz başlangıç ​​dizini değeri.",
        "Start index must be greater than 0.": "Başlangıç dizini 0'dan büyük olmalıdır.",
        "Reversed order": "Ters sıralama",
        "Keystrokes that can be used in a list": "Listedeki kullanılabilecek tuş vuruşları",
        "Increase list item indent": "Liste ögesi girintisini artır",
        "Decrease list item indent": "Liste ögesi girintisini azalt",
        "Entering a to-do list": "Yapılacaklar listesi girmek",
        "Leaving a to-do list": "Yapılacaklar listesinden ayrılma",
        "Unlink": "Bağlantıyı kaldır",
        "Link": "Bağlantı",
        "Link URL": "Bağlantı Adresi",
        "Link URL must not be empty.": "Bağlantı URL'si boş olmamalıdır.",
        "Link image": "Resim bağlantısı",
        "Edit link": "Bağlantıyı değiştir",
        "Open link in new tab": "Yeni sekmede aç",
        "This link has no URL": "Bağlantı adresi yok",
        "Open in a new tab": "Yeni sekmede aç",
        "Downloadable": "İndirilebilir",
        "Create link": "Bağlantı oluştur",
        "Move out of a link": "Bir bağlantıdan çık",
        "Language": "Dil",
        "Choose language": "Dil seç",
        "Remove language": "Dili kaldır",
        "Increase indent": "Girintiyi arttır",
        "Decrease indent": "Girintiyi azalt",
        "image widget": "resim aracı",
        "Wrap text": "Metni kaydır",
        "Break text": "Metni böl",
        "In line": "Aynı hizada",
        "Side image": "Yan Görsel",
        "Full size image": "Tam Boyut Görsel",
        "Left aligned image": "Sola hizalı görsel",
        "Centered image": "Ortalanmış görsel",
        "Right aligned image": "Sağa hizalı görsel",
        "Change image text alternative": "Görsel alternatif yazısını değiştir",
        "Text alternative": "Yazı alternatifi",
        "Enter image caption": "Resim açıklaması gir",
        "Insert image": "Görsel Ekle",
        "Replace image": "Resmi değiştir",
        "Upload from computer": "Bilgisayardan yükle",
        "Replace from computer": "Bilgisayardan değiştir",
        "Upload image from computer": "Bilgisayardan görüntü yükle",
        "Image from computer": "Bilgisayardan görüntü",
        "From computer": "Bilgisayardan",
        "Replace image from computer": "Görüntüyü bilgisayardan değiştir",
        "Upload failed": "Yükleme başarsız",
        "Image toolbar": "Resim araç çubuğu",
        "Resize image": "Resmi boyutlandır",
        "Resize image to %0": "Resmi %0 ölçülerine boyutlandır",
        "Resize image to the original size": "Resmi orijinal büyüklüğüne al",
        "Resize image (in %0)": "Resmi yeniden boyutlandır (%0 olarak)",
        "Original": "Orijinal",
        "Custom image size": "Özel resim boyutu",
        "Custom": "Özel",
        "Image resize list": "Resim yeniden boyutlandırma listesi",
        "Insert image via URL": "URL ile görüntü ekle",
        "Insert via URL": "URL aracılığıyla ekle",
        "Image via URL": "URL aracılığıyla görsel",
        "Via URL": "URL'den",
        "Update image URL": "Görüntü URL'sini güncelle",
        "Caption for the image": "Resim için başlık",
        "Caption for image: %0": "Resim için başlık: %0",
        "The value must not be empty.": "Değer boş olmamalıdır.",
        "The value should be a plain number.": "Değer düz bir sayı olmalıdır.",
        "Uploading image": "Resim yükleniyor",
        "Image upload complete": "Resim yüklemesi tamamlandı",
        "Error during image upload": "Resim yükleme sırasında hata oluştu",
        "Image": "Görsel",
        "HTML object": "HTML nesnesi",
        "Insert HTML": "HTML ekle",
        "HTML snippet": "HTML snippet'i",
        "Paste raw HTML here...": "Ham HTML'yi buraya yapıştırın...",
        "Edit source": "Kaynağı düzenle",
        "Save changes": "Değişiklikleri kaydet",
        "No preview available": "Önizleme yok",
        "Empty snippet content": "Snippet içeriği boş",
        "Horizontal line": "Yatay çiizgi",
        "Yellow marker": "Sarı işaretleyici",
        "Green marker": "Yeşil işaretleyici",
        "Pink marker": "Pembe işaretleyici",
        "Blue marker": "Mavi işaretleyici",
        "Red pen": "Kırmızı kalem",
        "Green pen": "Yeşik kalem",
        "Remove highlight": "Vurgulamayı temizle",
        "Highlight": "Vurgu",
        "Text highlight toolbar": "Yazı Vurgulama Araç Çubuğu",
        "Paragraph": "Paragraf",
        "Heading": "Başlık",
        "Choose heading": "Başlık tipi seç",
        "Heading 1": "1. Seviye Başlık",
        "Heading 2": "2. Seviye Başlık",
        "Heading 3": "3. Seviye Başlık",
        "Heading 4": "4. Seviye Başlık",
        "Heading 5": "5. Seviye Başlık",
        "Heading 6": "6. Seviye Başlık",
        "Type your title": "Başlığınızı yazınız",
        "Type or paste your content here.": "İçeriğinizi buraya yapıştırın yada yazın.",
        "Font Size": "Yazı Boyutu",
        "Tiny": "Çok Küçük",
        "Small": "Küçük",
        "Big": "Büyük",
        "Huge": "Çok Büyük",
        "Font Family": "Yazı Tipi Ailesi",
        "Default": "Varsayılan",
        "Font Color": "Yazı Tipi Rengi",
        "Font Background Color": "Yazı Tipi Arkaplan Rengi",
        "Document colors": "Belge Rengi",
        "Find and replace": "Bul ve değiştir",
        "Find in text…": "Metinde bul...",
        "Find": "Bul",
        "Previous result": "Önceki sonuç",
        "Next result": "Sonraki sonuç",
        "Replace": "Değiştir",
        "Replace all": "Hepsini değiştir",
        "Match case": "Büyük küçük harfe duyarlı",
        "Whole words only": "Sadece bütün kelimeler",
        "Replace with…": "Şununla değiştir...",
        "Text to find must not be empty.": "Bulunacak metin boş bırakılmamalıdır.",
        "Tip: Find some text first in order to replace it.": "İpucu: Değiştirmek için önce bir metin bul.",
        "Advanced options": "Gelişmiş seçenekler",
        "Find in the document": "Belgede bul",
        "Insert a soft break (a <code>&lt;br&gt;</code> element)": "Değişebilir sayfa sonu ekle (bir <code><br></code> ögesi)",
        "Insert a hard break (a new paragraph)": "Değişmez sayfa sonu ekle (yeni bir paragraf)",
        "Cancel": "İptal",
        "Clear": "Temizle",
        "Remove color": "Rengi Sil",
        "Restore default": "Varsayılanı geri yükle",
        "Save": "Kaydet",
        "Show more items": "Daha fazla öğe göster",
        "%0 of %1": "%0/%1",
        "Cannot upload file:": "Dosya yüklenemedi:",
        "Rich Text Editor. Editing area: %0": "Zengin Metin Editörü.Düzenleme alanı: %0",
        "Insert with file manager": "Dosya yöneticisiyle ekle",
        "Replace with file manager": "Dosya yöneticisiyle değiştirin",
        "Insert image with file manager": "Dosya yöneticisiyle görüntü ekleyin",
        "Replace image with file manager": "Resmi dosya yöneticisiyle değiştir",
        "File": "Dosya",
        "With file manager": "Dosya yöneticisi ile",
        "Toggle caption off": "Açıklamayı kapat",
        "Toggle caption on": "Açıklamayı aç",
        "Content editing keystrokes": "İçerik düzenleme tuş vuruşları",
        "These keyboard shortcuts allow for quick access to content editing features.": "Bu klavye kısayolları içerik düzenleme özelliklerine hızlı erişim sağlar.",
        "User interface and content navigation keystrokes": "Kullanıcı arayüzü ve içerik gezinme tuş vuruşları",
        "Use the following keystrokes for more efficient navigation in the CKEditor 5 user interface.": "CKEditor 5 kullanıcı arayüzünde daha etkili gezinti için aşağıdaki tuş vuruşlarını kullanın.",
        "Close contextual balloons, dropdowns, and dialogs": "Bağlamsal balonları, açılır menüleri ve iletişim kutularını kapat",
        "Open the accessibility help dialog": "Erişilebilirlik yardımı iletişim kutusunu aç",
        "Move focus between form fields (inputs, buttons, etc.)": "Odağı, form alanları (girdiler, düğmeler vb.) arasında taşı",
        "Move focus to the menu bar, navigate between menu bars": "Odağı menü çubuğuna taşıyın, menü çubukları arasında gezinin",
        "Move focus to the toolbar, navigate between toolbars": "Odağı araç çubuğuna taşı, araç çubukları arasında gezin",
        "Navigate through the toolbar or menu bar": "Araç çubuğu veya menü çubuğunda gezinme",
        "Execute the currently focused button. Executing buttons that interact with the editor content moves the focus back to the content.": "O anda odaklanılan düğmeyi çalıştırın. Düzenleyici içeriğiyle etkileşime giren düğmelerin çalıştırılması, odağı içeriğe geri taşır.",
        "Accept": "Kabul et",
        "Insert code block": "Kod bloğu ekle",
        "Plain text": "Düz metin",
        "Leaving %0 code snippet": "%0 kod parçacığından ayrılınıyor",
        "Entering %0 code snippet": "%0 kod parçacığına girmek",
        "Entering code snippet": "Kod parçacığına girmek",
        "Leaving code snippet": "Kod parçacığından ayrılma",
        "Code block": "Kod bloku",
        "Copy selected content": "Seçilen içeriği kopyala",
        "Paste content": "İçeriği yapıştır",
        "Paste content as plain text": "İçeriği düz metin olarak yapıştır",
        "Insert image or file": "Resim veya dosya ekleyin",
        "Could not obtain resized image URL.": "Yeniden boyutlandırılmış resim URL’si alınamadı",
        "Selecting resized image failed": "Yeniden boyutlandırılan resim seçilemedi",
        "Could not insert image at the current position.": "Resim mevcut konumda eklenemedi.",
        "Inserting image failed": "Resim eklenemedi",
        "Open file manager": "Dosya yöneticisini aç",
        "Cannot determine a category for the uploaded file.": "Yüklenen dosya için bir kategori belirlenemiyor.",
        "Cannot access default workspace.": "Varsayılan çalışma alanına erişilemiyor.",
        "Edit image": "Görüntüyü düzenle",
        "Processing the edited image.": "Düzenlenen görüntü işleniyor.",
        "Server failed to process the image.": "Sunucu görüntüyü işlemede başarısız oldu.",
        "Failed to determine category of edited image.": "Düzenlenen görselin kategorisinin belirlenmesi başarısız oldu.",
        "Block quote": "Alıntı",
        "Bold": "Kalın",
        "Italic": "İtalik",
        "Underline": "Altı Çizgili",
        "Code": "Kod",
        "Strikethrough": "Üstü çizili",
        "Subscript": "Alt Simge",
        "Superscript": "Üst Simge",
        "Italic text": "İtalik metin",
        "Move out of an inline code style": "Satır içi kod stilinden çık",
        "Bold text": "Kalın yazı",
        "Underline text": "Metnin altını çiz",
        "Strikethrough text": "Metnin üstünü çiz",
        "Saving changes": "Değişiklikler Kaydediliyor",
        "Revert autoformatting action": "Otomatik biçimlendirme işlemini geri al",
        "Align left": "Sola hizala",
        "Align right": "Sağa hizala",
        "Align center": "Ortala",
        "Justify": "İki yana yasla",
        "Text alignment": "Yazı hizalama",
        "Text alignment toolbar": "Yazı Hizlama Araç Çubuğu"
      }
    },
    "en": {
      dictionary: {
        "Page Number": "Page Number",
        "Preview": "Preview",
        "User Guide": "Guide",
        "Words: %0": "Words: %0",
        "Characters: %0": "Characters: %0",
        "Widget toolbar": "Widget toolbar",
        "Insert paragraph before block": "Insert paragraph before block",
        "Insert paragraph after block": "Insert paragraph after block",
        "Press Enter to type after or press Shift + Enter to type before the widget": "Press Enter to type after or press Shift + Enter to type before the widget",
        "Keystrokes that can be used when a widget is selected (for example: image, table, etc.)": "Keystrokes that can be used when a widget is selected (for example: image, table, etc.)",
        "Insert a new paragraph directly after a widget": "Insert a new paragraph directly after a widget",
        "Insert a new paragraph directly before a widget": "Insert a new paragraph directly before a widget",
        "Move the caret to allow typing directly before a widget": "Move the caret to allow typing directly before a widget",
        "Move the caret to allow typing directly after a widget": "Move the caret to allow typing directly after a widget",
        "Move focus from an editable area back to the parent widget": "Move focus from an editable area back to the parent widget",
        "Upload in progress": "Upload in progress",
        "Undo": "Undo",
        "Redo": "Redo",
        "Rich Text Editor": "Rich Text Editor",
        "Editor editing area: %0": "Editor editing area: %0",
        "Edit block": "Edit block",
        "Click to edit block": "Click to edit block",
        "Drag to move": "Drag to move",
        "Next": "Next",
        "Previous": "Previous",
        "Editor toolbar": "Editor toolbar",
        "Dropdown toolbar": "Dropdown toolbar",
        "Black": "Black",
        "Dim grey": "Dim grey",
        "Grey": "Grey",
        "Light grey": "Light grey",
        "White": "White",
        "Red": "Red",
        "Orange": "Orange",
        "Yellow": "Yellow",
        "Light green": "Light green",
        "Green": "Green",
        "Aquamarine": "Aquamarine",
        "Turquoise": "Turquoise",
        "Light blue": "Light blue",
        "Blue": "Blue",
        "Purple": "Purple",
        "Editor block content toolbar": "Editor block content toolbar",
        "Editor contextual toolbar": "Editor contextual toolbar",
        "HEX": "HEX",
        "No results found": "No results found",
        "No searchable items": "No searchable items",
        "Editor dialog": "Editor dialog",
        "Close": "Close",
        "Help Contents. To close this dialog press ESC.": "Help Contents. To close this dialog press ESC.",
        "Below, you can find a list of keyboard shortcuts that can be used in the editor.": "Below, you can find a list of keyboard shortcuts that can be used in the editor.",
        "(may require <kbd>Fn</kbd>)": "(may require <kbd>Fn</kbd>)",
        "Accessibility": "Accessibility",
        "Accessibility help": "Accessibility help",
        "Press %0 for help.": "Press %0 for help.",
        "Move focus in and out of an active dialog window": "Move focus in and out of an active dialog window",
        "MENU_BAR_MENU_FILE": "File",
        "MENU_BAR_MENU_EDIT": "Edit",
        "MENU_BAR_MENU_VIEW": "View",
        "MENU_BAR_MENU_INSERT": "Insert",
        "MENU_BAR_MENU_FORMAT": "Format",
        "MENU_BAR_MENU_TOOLS": "Tools",
        "MENU_BAR_MENU_HELP": "Help",
        "MENU_BAR_MENU_TEXT": "Text",
        "MENU_BAR_MENU_FONT": "Font",
        "Editor menu bar": "Editor menu bar",
        "Please enter a valid color (e.g. \"ff0000\").": "Please enter a valid color (e.g. \"ff0000\").",
        "Insert table": "Insert table",
        "Header column": "Header column",
        "Insert column left": "Insert column left",
        "Insert column right": "Insert column right",
        "Delete column": "Delete column",
        "Select column": "Select column",
        "Column": "Column",
        "Header row": "Header row",
        "Insert row below": "Insert row below",
        "Insert row above": "Insert row above",
        "Delete row": "Delete row",
        "Select row": "Select row",
        "Row": "Row",
        "Merge cell up": "Merge cell up",
        "Merge cell right": "Merge cell right",
        "Merge cell down": "Merge cell down",
        "Merge cell left": "Merge cell left",
        "Split cell vertically": "Split cell vertically",
        "Split cell horizontally": "Split cell horizontally",
        "Merge cells": "Merge cells",
        "Table toolbar": "Table toolbar",
        "Table properties": "Table properties",
        "Cell properties": "Cell properties",
        "Border": "Border",
        "Style": "Style",
        "Width": "Width",
        "Height": "Height",
        "Color": "Color",
        "Background": "Background",
        "Padding": "Padding",
        "Dimensions": "Dimensions",
        "Table cell text alignment": "Table cell text alignment",
        "Alignment": "Alignment",
        "Horizontal text alignment toolbar": "Horizontal text alignment toolbar",
        "Vertical text alignment toolbar": "Vertical text alignment toolbar",
        "Table alignment toolbar": "Table alignment toolbar",
        "None": "None",
        "Solid": "Solid",
        "Dotted": "Dotted",
        "Dashed": "Dashed",
        "Double": "Double",
        "Groove": "Groove",
        "Ridge": "Ridge",
        "Inset": "Inset",
        "Outset": "Outset",
        "Align cell text to the left": "Align cell text to the left",
        "Align cell text to the center": "Align cell text to the center",
        "Align cell text to the right": "Align cell text to the right",
        "Justify cell text": "Justify cell text",
        "Align cell text to the top": "Align cell text to the top",
        "Align cell text to the middle": "Align cell text to the middle",
        "Align cell text to the bottom": "Align cell text to the bottom",
        "Align table to the left": "Align table to the left",
        "Center table": "Center table",
        "Align table to the right": "Align table to the right",
        "The color is invalid. Try \"#FF0000\" or \"rgb(255,0,0)\" or \"red\".": "The color is invalid. Try \"#FF0000\" or \"rgb(255,0,0)\" or \"red\".",
        "The value is invalid. Try \"10px\" or \"2em\" or simply \"2\".": "The value is invalid. Try \"10px\" or \"2em\" or simply \"2\".",
        "Color picker": "Color picker",
        "Enter table caption": "Enter table caption",
        "Keystrokes that can be used in a table cell": "Keystrokes that can be used in a table cell",
        "Move the selection to the next cell": "Move the selection to the next cell",
        "Move the selection to the previous cell": "Move the selection to the previous cell",
        "Insert a new table row (when in the last cell of a table)": "Insert a new table row (when in the last cell of a table)",
        "Navigate through the table": "Navigate through the table",
        "Table": "Table",
        "Styles": "Styles",
        "Multiple styles": "Multiple styles",
        "Block styles": "Block styles",
        "Text styles": "Text styles",
        "Special characters": "Special characters",
        "All": "All",
        "Arrows": "Arrows",
        "Currency": "Currency",
        "Latin": "Latin",
        "Mathematical": "Mathematical",
        "Text": "Text",
        "leftwards simple arrow": "leftwards simple arrow",
        "rightwards simple arrow": "rightwards simple arrow",
        "upwards simple arrow": "upwards simple arrow",
        "downwards simple arrow": "downwards simple arrow",
        "leftwards double arrow": "leftwards double arrow",
        "rightwards double arrow": "rightwards double arrow",
        "upwards double arrow": "upwards double arrow",
        "downwards double arrow": "downwards double arrow",
        "leftwards dashed arrow": "leftwards dashed arrow",
        "rightwards dashed arrow": "rightwards dashed arrow",
        "upwards dashed arrow": "upwards dashed arrow",
        "downwards dashed arrow": "downwards dashed arrow",
        "leftwards arrow to bar": "leftwards arrow to bar",
        "rightwards arrow to bar": "rightwards arrow to bar",
        "upwards arrow to bar": "upwards arrow to bar",
        "downwards arrow to bar": "downwards arrow to bar",
        "up down arrow with base": "up down arrow with base",
        "back with leftwards arrow above": "back with leftwards arrow above",
        "end with leftwards arrow above": "end with leftwards arrow above",
        "on with exclamation mark with left right arrow above": "on with exclamation mark with left right arrow above",
        "soon with rightwards arrow above": "soon with rightwards arrow above",
        "top with upwards arrow above": "top with upwards arrow above",
        "Dollar sign": "Dollar sign",
        "Euro sign": "Euro sign",
        "Yen sign": "Yen sign",
        "Pound sign": "Pound sign",
        "Cent sign": "Cent sign",
        "Euro-currency sign": "Euro-currency sign",
        "Colon sign": "Colon sign",
        "Cruzeiro sign": "Cruzeiro sign",
        "French franc sign": "French franc sign",
        "Lira sign": "Lira sign",
        "Currency sign": "Currency sign",
        "Bitcoin sign": "Bitcoin sign",
        "Mill sign": "Mill sign",
        "Naira sign": "Naira sign",
        "Peseta sign": "Peseta sign",
        "Rupee sign": "Rupee sign",
        "Won sign": "Won sign",
        "New sheqel sign": "New sheqel sign",
        "Dong sign": "Dong sign",
        "Kip sign": "Kip sign",
        "Tugrik sign": "Tugrik sign",
        "Drachma sign": "Drachma sign",
        "German penny sign": "German penny sign",
        "Peso sign": "Peso sign",
        "Guarani sign": "Guarani sign",
        "Austral sign": "Austral sign",
        "Hryvnia sign": "Hryvnia sign",
        "Cedi sign": "Cedi sign",
        "Livre tournois sign": "Livre tournois sign",
        "Spesmilo sign": "Spesmilo sign",
        "Tenge sign": "Tenge sign",
        "Indian rupee sign": "Indian rupee sign",
        "Turkish lira sign": "Turkish lira sign",
        "Nordic mark sign": "Nordic mark sign",
        "Manat sign": "Manat sign",
        "Ruble sign": "Ruble sign",
        "Latin capital letter a with macron": "Latin capital letter a with macron",
        "Latin small letter a with macron": "Latin small letter a with macron",
        "Latin capital letter a with breve": "Latin capital letter a with breve",
        "Latin small letter a with breve": "Latin small letter a with breve",
        "Latin capital letter a with ogonek": "Latin capital letter a with ogonek",
        "Latin small letter a with ogonek": "Latin small letter a with ogonek",
        "Latin capital letter c with acute": "Latin capital letter c with acute",
        "Latin small letter c with acute": "Latin small letter c with acute",
        "Latin capital letter c with circumflex": "Latin capital letter c with circumflex",
        "Latin small letter c with circumflex": "Latin small letter c with circumflex",
        "Latin capital letter c with dot above": "Latin capital letter c with dot above",
        "Latin small letter c with dot above": "Latin small letter c with dot above",
        "Latin capital letter c with caron": "Latin capital letter c with caron",
        "Latin small letter c with caron": "Latin small letter c with caron",
        "Latin capital letter d with caron": "Latin capital letter d with caron",
        "Latin small letter d with caron": "Latin small letter d with caron",
        "Latin capital letter d with stroke": "Latin capital letter d with stroke",
        "Latin small letter d with stroke": "Latin small letter d with stroke",
        "Latin capital letter e with macron": "Latin capital letter e with macron",
        "Latin small letter e with macron": "Latin small letter e with macron",
        "Latin capital letter e with breve": "Latin capital letter e with breve",
        "Latin small letter e with breve": "Latin small letter e with breve",
        "Latin capital letter e with dot above": "Latin capital letter e with dot above",
        "Latin small letter e with dot above": "Latin small letter e with dot above",
        "Latin capital letter e with ogonek": "Latin capital letter e with ogonek",
        "Latin small letter e with ogonek": "Latin small letter e with ogonek",
        "Latin capital letter e with caron": "Latin capital letter e with caron",
        "Latin small letter e with caron": "Latin small letter e with caron",
        "Latin capital letter g with circumflex": "Latin capital letter g with circumflex",
        "Latin small letter g with circumflex": "Latin small letter g with circumflex",
        "Latin capital letter g with breve": "Latin capital letter g with breve",
        "Latin small letter g with breve": "Latin small letter g with breve",
        "Latin capital letter g with dot above": "Latin capital letter g with dot above",
        "Latin small letter g with dot above": "Latin small letter g with dot above",
        "Latin capital letter g with cedilla": "Latin capital letter g with cedilla",
        "Latin small letter g with cedilla": "Latin small letter g with cedilla",
        "Latin capital letter h with circumflex": "Latin capital letter h with circumflex",
        "Latin small letter h with circumflex": "Latin small letter h with circumflex",
        "Latin capital letter h with stroke": "Latin capital letter h with stroke",
        "Latin small letter h with stroke": "Latin small letter h with stroke",
        "Latin capital letter i with tilde": "Latin capital letter i with tilde",
        "Latin small letter i with tilde": "Latin small letter i with tilde",
        "Latin capital letter i with macron": "Latin capital letter i with macron",
        "Latin small letter i with macron": "Latin small letter i with macron",
        "Latin capital letter i with breve": "Latin capital letter i with breve",
        "Latin small letter i with breve": "Latin small letter i with breve",
        "Latin capital letter i with ogonek": "Latin capital letter i with ogonek",
        "Latin small letter i with ogonek": "Latin small letter i with ogonek",
        "Latin capital letter i with dot above": "Latin capital letter i with dot above",
        "Latin small letter dotless i": "Latin small letter dotless i",
        "Latin capital ligature ij": "Latin capital ligature ij",
        "Latin small ligature ij": "Latin small ligature ij",
        "Latin capital letter j with circumflex": "Latin capital letter j with circumflex",
        "Latin small letter j with circumflex": "Latin small letter j with circumflex",
        "Latin capital letter k with cedilla": "Latin capital letter k with cedilla",
        "Latin small letter k with cedilla": "Latin small letter k with cedilla",
        "Latin small letter kra": "Latin small letter kra",
        "Latin capital letter l with acute": "Latin capital letter l with acute",
        "Latin small letter l with acute": "Latin small letter l with acute",
        "Latin capital letter l with cedilla": "Latin capital letter l with cedilla",
        "Latin small letter l with cedilla": "Latin small letter l with cedilla",
        "Latin capital letter l with caron": "Latin capital letter l with caron",
        "Latin small letter l with caron": "Latin small letter l with caron",
        "Latin capital letter l with middle dot": "Latin capital letter l with middle dot",
        "Latin small letter l with middle dot": "Latin small letter l with middle dot",
        "Latin capital letter l with stroke": "Latin capital letter l with stroke",
        "Latin small letter l with stroke": "Latin small letter l with stroke",
        "Latin capital letter n with acute": "Latin capital letter n with acute",
        "Latin small letter n with acute": "Latin small letter n with acute",
        "Latin capital letter n with cedilla": "Latin capital letter n with cedilla",
        "Latin small letter n with cedilla": "Latin small letter n with cedilla",
        "Latin capital letter n with caron": "Latin capital letter n with caron",
        "Latin small letter n with caron": "Latin small letter n with caron",
        "Latin small letter n preceded by apostrophe": "Latin small letter n preceded by apostrophe",
        "Latin capital letter eng": "Latin capital letter eng",
        "Latin small letter eng": "Latin small letter eng",
        "Latin capital letter o with macron": "Latin capital letter o with macron",
        "Latin small letter o with macron": "Latin small letter o with macron",
        "Latin capital letter o with breve": "Latin capital letter o with breve",
        "Latin small letter o with breve": "Latin small letter o with breve",
        "Latin capital letter o with double acute": "Latin capital letter o with double acute",
        "Latin small letter o with double acute": "Latin small letter o with double acute",
        "Latin capital ligature oe": "Latin capital ligature oe",
        "Latin small ligature oe": "Latin small ligature oe",
        "Latin capital letter r with acute": "Latin capital letter r with acute",
        "Latin small letter r with acute": "Latin small letter r with acute",
        "Latin capital letter r with cedilla": "Latin capital letter r with cedilla",
        "Latin small letter r with cedilla": "Latin small letter r with cedilla",
        "Latin capital letter r with caron": "Latin capital letter r with caron",
        "Latin small letter r with caron": "Latin small letter r with caron",
        "Latin capital letter s with acute": "Latin capital letter s with acute",
        "Latin small letter s with acute": "Latin small letter s with acute",
        "Latin capital letter s with circumflex": "Latin capital letter s with circumflex",
        "Latin small letter s with circumflex": "Latin small letter s with circumflex",
        "Latin capital letter s with cedilla": "Latin capital letter s with cedilla",
        "Latin small letter s with cedilla": "Latin small letter s with cedilla",
        "Latin capital letter s with caron": "Latin capital letter s with caron",
        "Latin small letter s with caron": "Latin small letter s with caron",
        "Latin capital letter t with cedilla": "Latin capital letter t with cedilla",
        "Latin small letter t with cedilla": "Latin small letter t with cedilla",
        "Latin capital letter t with caron": "Latin capital letter t with caron",
        "Latin small letter t with caron": "Latin small letter t with caron",
        "Latin capital letter t with stroke": "Latin capital letter t with stroke",
        "Latin small letter t with stroke": "Latin small letter t with stroke",
        "Latin capital letter u with tilde": "Latin capital letter u with tilde",
        "Latin small letter u with tilde": "Latin small letter u with tilde",
        "Latin capital letter u with macron": "Latin capital letter u with macron",
        "Latin small letter u with macron": "Latin small letter u with macron",
        "Latin capital letter u with breve": "Latin capital letter u with breve",
        "Latin small letter u with breve": "Latin small letter u with breve",
        "Latin capital letter u with ring above": "Latin capital letter u with ring above",
        "Latin small letter u with ring above": "Latin small letter u with ring above",
        "Latin capital letter u with double acute": "Latin capital letter u with double acute",
        "Latin small letter u with double acute": "Latin small letter u with double acute",
        "Latin capital letter u with ogonek": "Latin capital letter u with ogonek",
        "Latin small letter u with ogonek": "Latin small letter u with ogonek",
        "Latin capital letter w with circumflex": "Latin capital letter w with circumflex",
        "Latin small letter w with circumflex": "Latin small letter w with circumflex",
        "Latin capital letter y with circumflex": "Latin capital letter y with circumflex",
        "Latin small letter y with circumflex": "Latin small letter y with circumflex",
        "Latin capital letter y with diaeresis": "Latin capital letter y with diaeresis",
        "Latin capital letter z with acute": "Latin capital letter z with acute",
        "Latin small letter z with acute": "Latin small letter z with acute",
        "Latin capital letter z with dot above": "Latin capital letter z with dot above",
        "Latin small letter z with dot above": "Latin small letter z with dot above",
        "Latin capital letter z with caron": "Latin capital letter z with caron",
        "Latin small letter z with caron": "Latin small letter z with caron",
        "Latin small letter long s": "Latin small letter long s",
        "Less-than sign": "Less-than sign",
        "Greater-than sign": "Greater-than sign",
        "Less-than or equal to": "Less-than or equal to",
        "Greater-than or equal to": "Greater-than or equal to",
        "En dash": "En dash",
        "Em dash": "Em dash",
        "Macron": "Macron",
        "Overline": "Overline",
        "Degree sign": "Degree sign",
        "Minus sign": "Minus sign",
        "Plus-minus sign": "Plus-minus sign",
        "Division sign": "Division sign",
        "Fraction slash": "Fraction slash",
        "Multiplication sign": "Multiplication sign",
        "Latin small letter f with hook": "Latin small letter f with hook",
        "Integral": "Integral",
        "N-ary summation": "N-ary summation",
        "Infinity": "Infinity",
        "Square root": "Square root",
        "Tilde operator": "Tilde operator",
        "Approximately equal to": "Approximately equal to",
        "Almost equal to": "Almost equal to",
        "Not equal to": "Not equal to",
        "Identical to": "Identical to",
        "Element of": "Element of",
        "Not an element of": "Not an element of",
        "Contains as member": "Contains as member",
        "N-ary product": "N-ary product",
        "Logical and": "Logical and",
        "Logical or": "Logical or",
        "Not sign": "Not sign",
        "Intersection": "Intersection",
        "Union": "Union",
        "Partial differential": "Partial differential",
        "For all": "For all",
        "There exists": "There exists",
        "Empty set": "Empty set",
        "Nabla": "Nabla",
        "Asterisk operator": "Asterisk operator",
        "Proportional to": "Proportional to",
        "Angle": "Angle",
        "Vulgar fraction one quarter": "Vulgar fraction one quarter",
        "Vulgar fraction one half": "Vulgar fraction one half",
        "Vulgar fraction three quarters": "Vulgar fraction three quarters",
        "Single left-pointing angle quotation mark": "Single left-pointing angle quotation mark",
        "Single right-pointing angle quotation mark": "Single right-pointing angle quotation mark",
        "Left-pointing double angle quotation mark": "Left-pointing double angle quotation mark",
        "Right-pointing double angle quotation mark": "Right-pointing double angle quotation mark",
        "Left single quotation mark": "Left single quotation mark",
        "Right single quotation mark": "Right single quotation mark",
        "Left double quotation mark": "Left double quotation mark",
        "Right double quotation mark": "Right double quotation mark",
        "Single low-9 quotation mark": "Single low-9 quotation mark",
        "Double low-9 quotation mark": "Double low-9 quotation mark",
        "Inverted exclamation mark": "Inverted exclamation mark",
        "Inverted question mark": "Inverted question mark",
        "Two dot leader": "Two dot leader",
        "Horizontal ellipsis": "Horizontal ellipsis",
        "Double dagger": "Double dagger",
        "Per mille sign": "Per mille sign",
        "Per ten thousand sign": "Per ten thousand sign",
        "Double exclamation mark": "Double exclamation mark",
        "Question exclamation mark": "Question exclamation mark",
        "Exclamation question mark": "Exclamation question mark",
        "Double question mark": "Double question mark",
        "Copyright sign": "Copyright sign",
        "Registered sign": "Registered sign",
        "Trade mark sign": "Trade mark sign",
        "Section sign": "Section sign",
        "Paragraph sign": "Paragraph sign",
        "Reversed paragraph sign": "Reversed paragraph sign",
        "Character categories": "Character categories",
        "Source": "Source",
        "Show source": "Show source",
        "Show blocks": "Show blocks",
        "Select all": "Select all",
        "Disable editing": "Disable editing",
        "Enable editing": "Enable editing",
        "Previous editable region": "Previous editable region",
        "Next editable region": "Next editable region",
        "Navigate editable regions": "Navigate editable regions",
        "Remove Format": "Remove Format",
        "Page break": "Page break",
        "media widget": "media widget",
        "Media URL": "Media URL",
        "Paste the media URL in the input.": "Paste the media URL in the input.",
        "Tip: Paste the URL into the content to embed faster.": "Tip: Paste the URL into the content to embed faster.",
        "The URL must not be empty.": "The URL must not be empty.",
        "This media URL is not supported.": "This media URL is not supported.",
        "Insert media": "Insert media",
        "Media": "Media",
        "Media toolbar": "Media toolbar",
        "Open media in new tab": "Open media in new tab",
        "Numbered List": "Numbered List",
        "Bulleted List": "Bulleted List",
        "To-do List": "To-do List",
        "Bulleted list styles toolbar": "Bulleted list styles toolbar",
        "Numbered list styles toolbar": "Numbered list styles toolbar",
        "Toggle the disc list style": "Toggle the disc list style",
        "Toggle the circle list style": "Toggle the circle list style",
        "Toggle the square list style": "Toggle the square list style",
        "Toggle the decimal list style": "Toggle the decimal list style",
        "Toggle the decimal with leading zero list style": "Toggle the decimal with leading zero list style",
        "Toggle the lower–roman list style": "Toggle the lower–roman list style",
        "Toggle the upper–roman list style": "Toggle the upper–roman list style",
        "Toggle the lower–latin list style": "Toggle the lower–latin list style",
        "Toggle the upper–latin list style": "Toggle the upper–latin list style",
        "Disc": "Disc",
        "Circle": "Circle",
        "Square": "Square",
        "Decimal": "Decimal",
        "Decimal with leading zero": "Decimal with leading zero",
        "Lower–roman": "Lower–roman",
        "Upper-roman": "Upper-roman",
        "Lower-latin": "Lower-latin",
        "Upper-latin": "Upper-latin",
        "List properties": "List properties",
        "Start at": "Start at",
        "Invalid start index value.": "Invalid start index value.",
        "Start index must be greater than 0.": "Start index must be greater than 0.",
        "Reversed order": "Reversed order",
        "Keystrokes that can be used in a list": "Keystrokes that can be used in a list",
        "Increase list item indent": "Increase list item indent",
        "Decrease list item indent": "Decrease list item indent",
        "Entering a to-do list": "Entering a to-do list",
        "Leaving a to-do list": "Leaving a to-do list",
        "Unlink": "Unlink",
        "Link": "Link",
        "Link URL": "Link URL",
        "Link URL must not be empty.": "Link URL must not be empty.",
        "Link image": "Link image",
        "Edit link": "Edit link",
        "Open link in new tab": "Open link in new tab",
        "This link has no URL": "This link has no URL",
        "Open in a new tab": "Open in a new tab",
        "Downloadable": "Downloadable",
        "Create link": "Create link",
        "Move out of a link": "Move out of a link",
        "Language": "Language",
        "Choose language": "Choose language",
        "Remove language": "Remove language",
        "Increase indent": "Increase indent",
        "Decrease indent": "Decrease indent",
        "image widget": "image widget",
        "Wrap text": "Wrap text",
        "Break text": "Break text",
        "In line": "In line",
        "Side image": "Side image",
        "Full size image": "Full size image",
        "Left aligned image": "Left aligned image",
        "Centered image": "Centered image",
        "Right aligned image": "Right aligned image",
        "Change image text alternative": "Change image text alternative",
        "Text alternative": "Text alternative",
        "Enter image caption": "Enter image caption",
        "Insert image": "Insert image",
        "Replace image": "Replace image",
        "Upload from computer": "Upload from computer",
        "Replace from computer": "Replace from computer",
        "Upload image from computer": "Upload image from computer",
        "Image from computer": "Image from computer",
        "From computer": "From computer",
        "Replace image from computer": "Replace image from computer",
        "Upload failed": "Upload failed",
        "Image toolbar": "Image toolbar",
        "Resize image": "Resize image",
        "Resize image to %0": "Resize image to %0",
        "Resize image to the original size": "Resize image to the original size",
        "Resize image (in %0)": "Resize image (in %0)",
        "Original": "Original",
        "Custom image size": "Custom image size",
        "Custom": "Custom",
        "Image resize list": "Image resize list",
        "Insert image via URL": "Insert image via URL",
        "Insert via URL": "Insert via URL",
        "Image via URL": "Image via URL",
        "Via URL": "Via URL",
        "Update image URL": "Update image URL",
        "Caption for the image": "Caption for the image",
        "Caption for image: %0": "Caption for image: %0",
        "The value must not be empty.": "The value must not be empty.",
        "The value should be a plain number.": "The value should be a plain number.",
        "Uploading image": "Uploading image",
        "Image upload complete": "Image upload complete",
        "Error during image upload": "Error during image upload",
        "Image": "Image",
        "HTML object": "HTML object",
        "Insert HTML": "Insert HTML",
        "HTML snippet": "HTML snippet",
        "Paste raw HTML here...": "Paste raw HTML here...",
        "Edit source": "Edit source",
        "Save changes": "Save changes",
        "No preview available": "No preview available",
        "Empty snippet content": "Empty snippet content",
        "Horizontal line": "Horizontal line",
        "Yellow marker": "Yellow marker",
        "Green marker": "Green marker",
        "Pink marker": "Pink marker",
        "Blue marker": "Blue marker",
        "Red pen": "Red pen",
        "Green pen": "Green pen",
        "Remove highlight": "Remove highlight",
        "Highlight": "Highlight",
        "Text highlight toolbar": "Text highlight toolbar",
        "Paragraph": "Paragraph",
        "Heading": "Heading",
        "Choose heading": "Choose heading",
        "Heading 1": "Heading 1",
        "Heading 2": "Heading 2",
        "Heading 3": "Heading 3",
        "Heading 4": "Heading 4",
        "Heading 5": "Heading 5",
        "Heading 6": "Heading 6",
        "Type your title": "Type your title",
        "Type or paste your content here.": "Type or paste your content here.",
        "Font Size": "Font Size",
        "Tiny": "Tiny",
        "Small": "Small",
        "Big": "Big",
        "Huge": "Huge",
        "Font Family": "Font Family",
        "Default": "Default",
        "Font Color": "Font Color",
        "Font Background Color": "Font Background Color",
        "Document colors": "Document colors",
        "Find and replace": "Find and replace",
        "Find in text…": "Find in text…",
        "Find": "Find",
        "Previous result": "Previous result",
        "Next result": "Next result",
        "Replace": "Replace",
        "Replace all": "Replace all",
        "Match case": "Match case",
        "Whole words only": "Whole words only",
        "Replace with…": "Replace with…",
        "Text to find must not be empty.": "Text to find must not be empty.",
        "Tip: Find some text first in order to replace it.": "Tip: Find some text first in order to replace it.",
        "Advanced options": "Advanced options",
        "Find in the document": "Find in the document",
        "Insert a soft break (a <code>&lt;br&gt;</code> element)": "Insert a soft break (a <code>&lt;br&gt;</code> element)",
        "Insert a hard break (a new paragraph)": "Insert a hard break (a new paragraph)",
        "Cancel": "Cancel",
        "Clear": "Clear",
        "Remove color": "Remove color",
        "Restore default": "Restore default",
        "Save": "Save",
        "Show more items": "Show more items",
        "%0 of %1": "%0 of %1",
        "Cannot upload file:": "Cannot upload file:",
        "Rich Text Editor. Editing area: %0": "Rich Text Editor. Editing area: %0",
        "Insert with file manager": "Insert with file manager",
        "Replace with file manager": "Replace with file manager",
        "Insert image with file manager": "Insert image with file manager",
        "Replace image with file manager": "Replace image with file manager",
        "File": "File",
        "With file manager": "With file manager",
        "Toggle caption off": "Toggle caption off",
        "Toggle caption on": "Toggle caption on",
        "Content editing keystrokes": "Content editing keystrokes",
        "These keyboard shortcuts allow for quick access to content editing features.": "These keyboard shortcuts allow for quick access to content editing features.",
        "User interface and content navigation keystrokes": "User interface and content navigation keystrokes",
        "Use the following keystrokes for more efficient navigation in the CKEditor 5 user interface.": "Use the following keystrokes for more efficient navigation in the CKEditor 5 user interface.",
        "Close contextual balloons, dropdowns, and dialogs": "Close contextual balloons, dropdowns, and dialogs",
        "Open the accessibility help dialog": "Open the accessibility help dialog",
        "Move focus between form fields (inputs, buttons, etc.)": "Move focus between form fields (inputs, buttons, etc.)",
        "Move focus to the menu bar, navigate between menu bars": "Move focus to the menu bar, navigate between menu bars",
        "Move focus to the toolbar, navigate between toolbars": "Move focus to the toolbar, navigate between toolbars",
        "Navigate through the toolbar or menu bar": "Navigate through the toolbar or menu bar",
        "Execute the currently focused button. Executing buttons that interact with the editor content moves the focus back to the content.": "Execute the currently focused button. Executing buttons that interact with the editor content moves the focus back to the content.",
        "Accept": "Accept",
        "Insert code block": "Insert code block",
        "Plain text": "Plain text",
        "Leaving %0 code snippet": "Leaving %0 code snippet",
        "Entering %0 code snippet": "Entering %0 code snippet",
        "Entering code snippet": "Entering code snippet",
        "Leaving code snippet": "Leaving code snippet",
        "Code block": "Code block",
        "Copy selected content": "Copy selected content",
        "Paste content": "Paste content",
        "Paste content as plain text": "Paste content as plain text",
        "Insert image or file": "Insert image or file",
        "Could not obtain resized image URL.": "Could not obtain resized image URL.",
        "Selecting resized image failed": "Selecting resized image failed",
        "Could not insert image at the current position.": "Could not insert image at the current position.",
        "Inserting image failed": "Inserting image failed",
        "Open file manager": "Open file manager",
        "Cannot determine a category for the uploaded file.": "Cannot determine a category for the uploaded file.",
        "Cannot access default workspace.": "Cannot access default workspace.",
        "Edit image": "Edit image",
        "Processing the edited image.": "Processing the edited image.",
        "Server failed to process the image.": "Server failed to process the image.",
        "Failed to determine category of edited image.": "Failed to determine category of edited image.",
        "Block quote": "Block quote",
        "Bold": "Bold",
        "Italic": "Italic",
        "Underline": "Underline",
        "Code": "Code",
        "Strikethrough": "Strikethrough",
        "Subscript": "Subscript",
        "Superscript": "Superscript",
        "Italic text": "Italic text",
        "Move out of an inline code style": "Move out of an inline code style",
        "Bold text": "Bold text",
        "Underline text": "Underline text",
        "Strikethrough text": "Strikethrough text",
        "Saving changes": "Saving changes",
        "Revert autoformatting action": "Revert autoformatting action",
        "Align left": "Align left",
        "Align right": "Align right",
        "Align center": "Align center",
        "Justify": "Justify",
        "Text alignment": "Text alignment",
        "Text alignment toolbar": "Text alignment toolbar"
      }
    }
  }
};
